CREATE TABLE user_email (
  Email_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	Email_Address VARCHAR(200) NOT NULL,
	Email_Rank TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	User_ID INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (User_ID),
	UNIQUE UN_User_Rank (User_ID, Email_Rank)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
