CREATE TABLE user_session (
	Session_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	Session_In INT(10) UNSIGNED NOT NULL,
	Session_InType ENUM('manual','auto') NOT NULL DEFAULT 'manual',
	Session_Out INT(10) UNSIGNED DEFAULT NULL,
	Session_OutType ENUM('manual','auto','app') DEFAULT NULL,
	Session_IP VARCHAR(39) NOT NULL,
	User_ID INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (Session_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
