CREATE DATABASE IF NOT EXISTS ocm_generic DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS ocm_generic.site_news (
	News_ID SMALLINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	News_Title VARCHAR(60) NOT NULL,
	News_Content TEXT NOT NULL,
	News_Epoch INT(10) UNSIGNED NOT NULL,
	News_Live INT(10) UNSIGNED NOT NULL,
	News_IP VARCHAR(39) NOT NULL,
	User_ID INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (News_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ocm_generic.news_comment (
	Comment_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	Comment_Title VARCHAR(60),
	Comment_Content TEXT NOT NULL,
    Comment_Epoch INT(10) UNSIGNED NOT NULL,
	News_IP VARCHAR(39) NOT NULL,
	User_ID INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (Comment_ID)
) ENGINE=InnoDB;
